spring.application.name=portfolio
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.show-sql=true

# CORS configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# API Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
